import subprocess
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT


def extract_js_function(source, name):
    start = source.index(f"function {name}")
    brace_start = source.index("{", start)
    depth = 0
    for index in range(brace_start, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return source[start:index + 1]
    raise AssertionError(f"Could not extract {name}")


class StaticUiTestCase(unittest.TestCase):
    def test_supabase_hosted_mode_assets_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertIn("@supabase/supabase-js@2", html)
        self.assertNotIn('id="supabaseConfigForm"', html)
        self.assertNotIn('id="supabaseUrl"', html)
        self.assertNotIn('id="supabaseAnonKey"', html)
        self.assertIn('const SUPABASE_URL = "https://sbqqylrnjfrrqwrdiiun.supabase.co"', js)
        self.assertIn("const SUPABASE_ANON_KEY =", js)
        self.assertIn("function initializeSupabase()", js)
        self.assertIn("function buildClient", js)
        self.assertIn("window.supabase.createClient", js)

    def test_gantt_view_assets_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="ganttChart"', html)
        self.assertIn('id="ganttScale"', html)
        self.assertIn('id="bulletinChart"', html)
        self.assertIn('id="bulletinScale"', html)
        self.assertIn('id="bulletinBoard"', html)
        self.assertIn('id="bulletinScrollInterval"', html)
        self.assertIn('id="bulletinScrollDuration"', html)
        self.assertIn('id="bulletinScrollInterval" type="number" min="5" max="300" step="5" value="30"', html)
        self.assertIn('id="bulletinScrollDuration" type="number" min="1" max="30" step="1" value="1"', html)
        self.assertIn("function renderGantt(", js)
        self.assertIn("function renderBulletinBoard()", js)
        self.assertIn("function renderGanttSurface(", js)
        self.assertIn("function getReservationHoursWithinWeek(", js)
        self.assertIn("Math.min(reservationEnd, weekEnd)", js)
        self.assertIn("Math.max(reservationStart, weekStart)", js)
        self.assertIn("function openBulletinFullscreen()", js)
        self.assertIn("function openBulletinWindow()", js)
        self.assertIn("function scheduleBulletinAutoScroll(options = {})", js)
        self.assertIn("function stopBulletinAutoScroll(", js)
        self.assertIn("function animateBulletinScroll(", js)
        self.assertIn("function stepBulletinAutoScroll()", js)
        self.assertIn("requestAnimationFrame", js)
        self.assertIn("animationFrameId", js)
        self.assertNotIn('behavior: "smooth"', js)
        self.assertIn("function getBulletinStickyOffset(", js)
        self.assertIn("function syncBulletinStickyOffset(", js)
        self.assertIn("function getBulletinBottomScrollTop(", js)
        self.assertIn("function updateBulletinScrollSettings()", js)
        self.assertIn('window.addEventListener("resize",', js)
        self.assertIn('document.addEventListener("fullscreenchange",', js)
        self.assertIn("function getGanttBarStyle", js)
        self.assertIn("function getBulletinGanttMetrics(", js)
        self.assertIn("function getBulletinGanttBarMarkup(", js)
        self.assertIn("intervalSeconds: 30", js)
        self.assertIn("durationSeconds: 1", js)
        self.assertNotIn("測試人：", js)
        self.assertNotIn("測試期間：", js)
        self.assertIn("project_name", js)

        self.assertIn("async function cancelProject", js)
        self.assertIn("async function completeProject", js)
        cancel_flow = js[js.index("async function cancelProject"):js.index("async function completeProject")]
        self.assertIn("window.prompt", cancel_flow)
        self.assertNotIn("window.confirm", cancel_flow)
        complete_flow = js[js.index("async function completeProject"):]
        self.assertIn("window.confirm", complete_flow)
        self.assertIn("專案完成", complete_flow)
        self.assertIn(".gantt-chart", css)
        self.assertIn(".gantt-bar", css)
        self.assertIn(".bulletin-panel", css)
        self.assertIn(".bulletin-wrap", css)
        self.assertIn("height: clamp(", css)
        self.assertIn("scroll-snap-type: y mandatory", css)
        self.assertIn("scroll-padding-top: 41px", css)
        self.assertIn(".bulletin-row", css)
        self.assertIn(".bulletin-controls", css)
        self.assertIn(".bulletin-bar", css)

    def test_reservation_form_has_project_name_and_no_week_schedule_panel(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('name="project_name"', html)
        self.assertIn('list="requesterNameOptions"', html)
        self.assertIn('list="requesterEmailOptions"', html)
        self.assertIn('value="PQE"', html)
        self.assertIn('id="requesterNameOptions"', html)
        self.assertIn('id="requesterEmailOptions"', html)
        self.assertIn('id="requesterNameMatches"', html)
        self.assertIn('id="requesterEmailMatches"', html)
        self.assertIn('name="test_condition"', html)
        self.assertNotIn('textarea name="notes" rows="3" placeholder=', html)
        self.assertIn("[hidden]", css)
        self.assertIn("project_name: payload.project_name.trim()", js)
        self.assertIn("function syncReservationEquipmentState()", js)
        self.assertIn("function isTruthyFlag(", js)
        self.assertIn("requires_test_condition", js)
        self.assertIn("test_condition", js)
        self.assertIn('.from("requester_directory")', js)
        self.assertIn("function loadRequesterDirectory()", js)
        self.assertIn("function renderRequesterOptions()", js)
        self.assertIn("function handleRequesterLookup", js)
        self.assertIn("function applyRequesterSuggestion", js)
        self.assertIn("function syncRequesterFields", js)
        self.assertIn(".typeahead-menu", css)
        self.assertNotIn('id="scheduleBoard"', html)
        self.assertNotIn("function renderWeek()", js)

    def test_legacy_excel_and_local_api_ui_is_removed(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertNotIn("/api/export.xlsx", html)
        self.assertNotIn("SharePoint Excel", html)
        self.assertNotIn('fetch("/api/', js)

    def test_dashboard_and_equipment_management_views_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="dashboardMetrics"', html)
        self.assertIn('data-view="reservation"', html)
        self.assertIn('data-view="equipment"', html)
        self.assertIn('data-view="requester"', html)
        self.assertIn('data-view="bulletin"', html)
        self.assertIn('id="equipmentFormTitle"', html)
        self.assertIn('id="equipmentCancelBtn"', html)
        self.assertIn('id="requesterForm"', html)
        self.assertIn('id="requesterSummary"', html)
        self.assertIn('id="requesterFormTitle"', html)
        self.assertIn('id="requesterCancelBtn"', html)
        self.assertIn('id="requesterResetBtn"', html)
        self.assertIn('name="requires_test_condition"', html)
        self.assertIn('name="equipment_spec"', html)
        self.assertIn('input name="capacity" type="text"', html)
        self.assertIn("可重疊預約量", js)
        self.assertNotIn('input name="capacity" type="number"', html)
        self.assertIn('select name="is_active"', html)
        self.assertIn('option value="validation"', html)
        self.assertIn("function renderDashboardMetrics()", js)
        self.assertIn("function startEditEquipment", js)
        self.assertIn("function syncEquipmentForm", js)
        self.assertIn("function cancelEquipmentEdit", js)
        self.assertIn("function submitRequester", js)
        self.assertIn("function renderRequesterSummary", js)
        self.assertIn("function startEditRequester", js)
        self.assertIn("function syncRequesterForm", js)
        self.assertIn("function cancelRequesterEdit", js)
        self.assertIn("function deleteRequester", js)
        self.assertIn('.order("is_active", { ascending: false })', js)
        self.assertIn(".filter((item) => item.is_active)", js)
        self.assertIn("function equipmentMatchesPayload", js)
        self.assertIn("function parseEquipmentCapacityLimit(", js)
        self.assertIn("equipment_spec", js)
        self.assertIn("equipmentSpecSupported", js)
        self.assertIn("equipment_spec.*does not exist", js)
        self.assertNotIn("function normalizeTestCondition(", js)
        self.assertNotIn("function testConditionsMatch(", js)
        self.assertNotIn("assertCompatibleTestCondition", js)
        self.assertIn('statusText.validation = "驗證中"', js)
        self.assertIn(".metrics-grid", css)
        self.assertIn(".workspace-tab", css)
        self.assertIn(".equipment-card-actions", css)
        self.assertIn(".requester-card", css)
        self.assertIn(".badge.validation", css)

    def test_gantt_reservation_detail_dialog_is_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="reservationDetailDialog"', html)
        self.assertIn('id="reservationDetailCopyBtn"', html)
        self.assertIn('id="reservationDetailCompleteBtn"', html)
        self.assertIn('id="reservationDetailCancelBtn"', html)
        self.assertIn(">專案完成<", html)
        self.assertIn(">專案取消<", html)
        self.assertIn('class="project-complete"', html)
        self.assertIn('class="form-actions reservation-detail-actions"', html)
        self.assertIn('class="reservation-status-actions"', html)
        self.assertIn('id="reservationEditEmail"', html)
        self.assertIn('id="reservationEditUnlockBtn"', html)
        self.assertIn('id="reservationEditSaveBtn"', html)
        self.assertIn("function openReservationDetail(", js)
        self.assertIn("function getReservationViewModel(", js)
        self.assertIn("const view = getReservationViewModel(reservation);", js)
        self.assertIn("function getReservationDetailText(", js)
        self.assertIn("function configureReservationEdit(", js)
        self.assertIn("function unlockReservationEdit(", js)
        self.assertIn("function saveReservationEdit(", js)
        self.assertIn("function validateShortenedReservationWindow(", js)
        self.assertIn("function emailMatchesReservation(", js)
        self.assertIn('action: "updated"', js)
        self.assertIn("project_name", js)
        self.assertIn("start_time", js)
        self.assertIn("end_time", js)
        self.assertIn("navigator.clipboard.writeText", js)
        self.assertIn("reservation.project_name", js)
        self.assertIn(".reservation-detail-dialog", css)
        self.assertIn(".detail-grid", css)
        self.assertIn(".reservation-edit-panel", css)

    def test_gantt_overlap_stacking_and_equipment_zoom_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="equipmentScheduleDialog"', html)
        self.assertIn('id="equipmentScheduleChart"', html)
        self.assertIn("function layoutStackedReservations(", js)
        self.assertIn("function getEquipmentViewModel(", js)
        self.assertIn("const equipmentView = getEquipmentViewModel(equipment);", js)
        self.assertIn("function getDefaultGanttMetrics(", js)
        self.assertIn("function getMainGanttBarMarkup(", js)
        self.assertIn("function getStackedGanttBarStyle(", js)
        self.assertIn("function getVisibleStackedReservations(", js)
        self.assertIn("function getGanttLaneSummary(", js)
        self.assertIn("function applyRightEdgeFill(", js)
        self.assertIn("function isSingleDayReservation(", js)
        self.assertIn("if (!isSingleDayReservation(item.reservation))", js)
        self.assertIn("gantt-overflow-chip", js)
        self.assertIn("function openEquipmentSchedule(", js)
        self.assertIn("renderEquipmentScheduleDialog", js)
        self.assertIn("equipment-zoom-btn", js)
        self.assertIn(".gantt-bar.compact-bar", css)
        self.assertIn(".gantt-bar.project-requester", css)
        self.assertIn(".gantt-bar.project-only", css)
        self.assertIn("min-height: 0", css)
        self.assertIn(".gantt-overflow-chip", css)
        self.assertIn(".equipment-schedule-dialog", css)
        self.assertIn(".equipment-zoom-btn", css)

    def test_gantt_year_header_segments_and_english_weekdays_are_present(self):
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('const dayNames = ["Sun.", "Mon.", "Tue.", "Wed.", "Thu.", "Fri.", "Sat."]', js)
        self.assertNotIn('const dayNames = ["週日"', js)
        self.assertIn("function getGanttYearSegments(", js)
        self.assertIn("function appendGanttYearHeader(", js)
        self.assertIn("appendGanttYearHeader(scale, range, variant);", js)
        self.assertIn("const minWidth = 220 + range.dayCount * dayWidth;", js)
        self.assertIn("scale.style.width = `${minWidth}px`;", js)
        self.assertIn("chart.style.width = `${minWidth}px`;", js)
        self.assertIn('scale.style.setProperty("--gantt-year-label-left"', js)
        self.assertIn('scale.style.setProperty("--gantt-year-label-right"', js)
        self.assertIn('label.className = "gantt-year-label";', js)
        self.assertIn("cell.appendChild(label);", js)
        self.assertIn(".gantt-year-cell", css)
        self.assertIn(".gantt-year-spacer", css)
        self.assertIn("overflow: clip", css)
        self.assertIn("text-align: left", css)
        self.assertIn(".gantt-year-label", css)
        self.assertIn("position: sticky", css)
        self.assertIn("left: var(--gantt-year-label-left", css)
        self.assertIn("right: var(--gantt-year-label-right", css)

        helper = extract_js_function(js, "getGanttYearSegments")
        script = helper + """
const segments = getGanttYearSegments({ start: new Date(2026, 11, 27), dayCount: 7 });
const actual = segments.map(({ year, span }) => ({ year, span }));
const expected = [{ year: 2026, span: 5 }, { year: 2027, span: 2 }];
if (JSON.stringify(actual) !== JSON.stringify(expected)) {
  console.error(JSON.stringify(actual));
  process.exit(1);
}
"""
        result = subprocess.run(["node", "-e", script], capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)

    def test_completed_reservations_release_time_and_render_soft_blue(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("function completeProject(", js)
        self.assertIn("function cancelProject(", js)
        self.assertIn('edit.textContent = "編輯"', js)
        self.assertNotIn('complete.textContent = "完成"', js)
        self.assertNotIn('cancel.textContent = "取消"', js)
        self.assertIn("function getEffectiveReservationStatus(", js)
        self.assertIn("function canCompleteReservation(", js)
        self.assertIn('panel.hidden = isReadOnly', js)
        self.assertIn('["cancelled", "checked_out"].includes(getEffectiveReservationStatus(reservation))', js)
        self.assertIn("statusLabel = statusText[effectiveStatus] || effectiveStatus", js)
        self.assertIn("return getReservationViewModel(reservation).detailRows", js)
        self.assertIn("checked_out:", js)
        self.assertIn('.neq("status", "checked_out")', js)
        self.assertIn("checked_out_at", js)
        self.assertIn('action: "completed"', js)
        self.assertIn("background: #dbeafe", css)
        self.assertIn("background: #dcfce7", css)
        self.assertIn("background: #ffedd5", css)
        self.assertIn(".gantt-bar.is-complete", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-pqe", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-senao", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-external", css)
        self.assertIn(".badge.checked_out", css)

    def test_reservation_list_is_paginated_and_split_by_project_status(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="reservationOpenTab"', html)
        self.assertIn('id="reservationClosedTab"', html)
        self.assertIn('id="reservationPrevPage"', html)
        self.assertIn('id="reservationNextPage"', html)
        self.assertIn('id="reservationPageLabel"', html)
        self.assertIn('status: "open"', js)
        self.assertIn('pageSize: 10', js)
        self.assertIn("function getReservationsWithinWeek(", js)
        self.assertIn("function setReservationListStatus(", js)
        self.assertIn("function moveReservationListPage(", js)
        self.assertIn("const pageReservations = filteredReservations.slice(", js)
        self.assertIn("getReservationsWithinWeek().filter", js)
        self.assertNotIn('.lt("start_time", toIso)', js)
        self.assertNotIn('.gt("end_time", fromIso)', js)
        self.assertIn(".reservation-list-toolbar", css)
        self.assertIn(".reservation-status-actions", css)

    def test_month_schedule_dialog_and_requester_categories_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="reservationCreateDialog"', html)
        self.assertIn('id="openReservationCreateDialogBtn"', html)
        self.assertIn('id="schedulePrevMonth"', html)
        self.assertIn('id="scheduleNextMonth"', html)
        self.assertIn('id="bulletinPrevMonth"', html)
        self.assertIn('id="bulletinNextMonth"', html)
        self.assertIn('id="reservationRequesterCategory"', html)
        self.assertIn('class="gantt-wrap gantt-schedule-wrap"', html)
        self.assertIn("function getMonthlyScheduleRange(", js)
        self.assertIn("const GANTT_DISPLAY_DAYS = 31;", js)
        self.assertIn("function getFixedGanttDisplayRange(", js)
        self.assertIn("dayCount: GANTT_DISPLAY_DAYS", js)
        self.assertIn("function getGanttDisplayDayWidth(", js)
        self.assertIn("getGanttDisplayDayWidth(document.querySelector(\".bulletin-wrap\"))", js)
        self.assertIn("function moveMainScheduleMonth(", js)
        self.assertIn("function extendMainScheduleRange(", js)
        self.assertIn("function handleMainGanttScroll(", js)
        self.assertIn("function getReservationsWithinRange(", js)
        self.assertIn("function openReservationCreateDialog(", js)
        self.assertIn("function openReservationFromGanttCell(", js)
        self.assertIn("function handleMainGanttLaneDoubleClick(", js)
        self.assertIn('lane.addEventListener("dblclick"', js)
        self.assertIn("handleMainGanttLaneDoubleClick(event, equipment, range, lane)", js)
        self.assertNotIn('lane.addEventListener("click"', js)
        self.assertIn("function getRequesterCategory(", js)
        self.assertIn('form.elements.end_time.value = ""', js)
        self.assertIn("range.dayCount", js)
        self.assertIn(".gantt-schedule-wrap", css)
        self.assertIn(".requester-category-pqe", css)
        self.assertIn(".requester-category-senao", css)
        self.assertIn(".requester-category-external", css)
        self.assertIn(".gantt-bar.requester-category-pqe", css)
        self.assertIn(".gantt-bar.requester-category-senao", css)
        self.assertIn(".gantt-bar.requester-category-external", css)
        self.assertIn(".gantt-schedule-wrap .gantt-bar-info", css)
        self.assertIn("function syncMainGanttBarInfo(", js)
        self.assertIn("info.style.transform", js)
        self.assertNotIn(".gantt-lane-frozen-info", css)
        self.assertIn(".reservation-row.requester-category-pqe", css)

    def test_gantt_supports_unbounded_month_navigation_and_horizontal_drag(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="schedulePrevMonth"', html)
        self.assertIn('id="scheduleNextMonth"', html)
        self.assertIn('id="scheduleRangeLabel"', html)
        self.assertIn('id="bulletinPrevMonth"', html)
        self.assertIn('id="bulletinNextMonth"', html)
        self.assertIn('id="bulletinMonthLabel"', html)
        self.assertIn("const SCHEDULE_EXTENSION_MONTHS = 6", js)
        self.assertIn("scheduleRangeStart", js)
        self.assertIn("scheduleRangeEnd", js)
        self.assertIn("scheduleRangeStart: addMonths(startOfDay(new Date()), -SCHEDULE_EXTENSION_MONTHS)", js)
        self.assertIn("scheduleRangeEnd: addMonths(addMonths(startOfDay(new Date()), 1), SCHEDULE_EXTENSION_MONTHS)", js)
        self.assertIn("function moveMainScheduleMonth(", js)
        self.assertIn("function extendMainScheduleRange(", js)
        self.assertIn("function handleMainGanttScroll(", js)
        self.assertIn("function bindGanttDrag(", js)
        self.assertIn("function scrollMainScheduleToDate(", js)
        self.assertIn("function getMainScheduleDayWidth(", js)
        self.assertIn("wrap.scrollLeft", js)
        self.assertIn("wrap.scrollWidth", js)
        self.assertIn("wrap.clientWidth", js)
        self.assertIn('ganttWrap?.addEventListener("scroll", handleMainGanttScroll', js)
        self.assertIn("addMonths(state.scheduleRangeStart, -SCHEDULE_EXTENSION_MONTHS)", js)
        self.assertIn("addMonths(state.scheduleRangeEnd, SCHEDULE_EXTENSION_MONTHS)", js)
        self.assertIn("cursor: default", css)
        self.assertIn("GANTT_DRAG_THRESHOLD_PX", js)
        self.assertIn("dragging: false", js)
        self.assertIn("Math.abs(deltaX) < GANTT_DRAG_THRESHOLD_PX", js)
        self.assertIn(".gantt-bar-info", css)
        self.assertIn(".gantt-schedule-wrap .gantt-bar-info", css)
        self.assertIn("function syncMainGanttBarInfo(", js)
        self.assertIn("info.style.transform", js)
        self.assertNotIn("gantt-lane-frozen-info", css)
        self.assertNotIn("frozenInfo", js)
        self.assertIn("function getReservationsIntersectingRange(", js)
        self.assertIn("const viewportStackedReservations", js)
        self.assertIn("getDefaultGanttMetrics(viewportStackCount)", js)
        self.assertIn("crossedMonth", js)
        self.assertIn(".gantt-schedule-wrap .gantt-bar-info", css)
        self.assertIn(".gantt-schedule-wrap .gantt-equipment-label", css)
        self.assertIn("position: sticky", css)

    def test_gantt_bars_and_reservation_rows_share_requester_category_tokens(self):
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn("const requesterCategory = getRequesterCategory(reservation);", js)
        self.assertIn('requester-category-${requesterCategory.key}', js)
        self.assertIn('requester-category-badge requester-category-${escapeHtml(requesterCategory.key)}', js)
        self.assertIn('const effectiveStatus = getEffectiveReservationStatus(reservation);', js)
        self.assertIn('tr.className = `reservation-row requester-category-${requesterCategory.key}${effectiveStatus === "checked_out" ? " is-complete" : ""}`;', js)
        self.assertIn("getRequesterCategory(reservation)", js)
        self.assertIn(".gantt-bar.requester-category-pqe", css)
        self.assertIn(".gantt-bar.requester-category-senao", css)
        self.assertIn(".gantt-bar.requester-category-external", css)
        self.assertIn(".bulletin-bar.requester-category-pqe", css)
        self.assertIn(".bulletin-bar.requester-category-senao", css)
        self.assertIn(".bulletin-bar.requester-category-external", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-pqe", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-senao", css)
        self.assertIn(".gantt-bar.is-complete.requester-category-external", css)
        self.assertIn(".reservation-row.requester-category-pqe", css)
        self.assertIn(".reservation-row.requester-category-senao", css)
        self.assertIn(".reservation-row.requester-category-external", css)
        self.assertIn(".reservation-row .requester-category-badge", css)

    def test_root_entry_is_the_real_frontend(self):
        root_html = (ROOT / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="reservationForm"', root_html)
        self.assertIn('./styles.css', root_html)
        self.assertIn('./app.js', root_html)
        self.assertNotIn("http-equiv=\"refresh\"", root_html)

    def test_capacity_text_manual_sql_is_present(self):
        sql = (STATIC / "supabase" / "manual" / "20260703_capacity_text.sql").read_text(encoding="utf-8")

        self.assertIn("alter table public.equipment", sql)
        self.assertIn("alter column capacity type text", sql)


if __name__ == "__main__":
    unittest.main()
