import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT


class StaticUiTestCase(unittest.TestCase):
    def test_supabase_hosted_mode_assets_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertIn("@supabase/supabase-js@2", html)
        self.assertNotIn('id="supabaseConfigForm"', html)
        self.assertNotIn('id="supabaseUrl"', html)
        self.assertNotIn('id="supabaseAnonKey"', html)
        self.assertIn('const SUPABASE_URL = "https://sbqqylrnjfrrqwrdiiun.supabase.co"', js)
        self.assertIn("const SUPABASE_ANON_KEY =", js)
        self.assertIn("function initializeSupabase()", js)
        self.assertIn("function buildClient", js)
        self.assertIn("window.supabase.createClient", js)

    def test_gantt_view_assets_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="ganttChart"', html)
        self.assertIn('id="ganttScale"', html)
        self.assertIn('id="bulletinChart"', html)
        self.assertIn('id="bulletinScale"', html)
        self.assertIn('id="bulletinBoard"', html)
        self.assertIn('id="bulletinSettings"', html)
        self.assertIn('id="bulletinSettingsToggle"', html)
        self.assertIn('id="bulletinSettingsPanel"', html)
        self.assertIn('aria-controls="bulletinSettingsPanel"', html)
        self.assertIn('aria-expanded="false"', html)
        self.assertNotIn('<details id="bulletinSettings" class="bulletin-settings" open>', html)
        self.assertIn('id="bulletinRangeSelect"', html)
        self.assertIn('<option value="7">1 週</option>', html)
        self.assertIn('<option value="14">2 週</option>', html)
        self.assertIn('<option value="28" selected>4 週</option>', html)
        self.assertIn('id="bulletinScrollInterval"', html)
        self.assertIn('id="bulletinScrollDuration"', html)
        self.assertIn("function renderGantt(", js)
        self.assertIn("function renderBulletinBoard(", js)
        self.assertIn("function renderGanttSurface(", js)
        self.assertIn("const BULLETIN_RANGE_DAY_OPTIONS = [7, 14, 28];", js)
        self.assertIn("const BULLETIN_DEFAULT_RANGE_DAYS = 28;", js)
        self.assertIn("bulletinRangeStart: startOfDay(new Date())", js)
        self.assertIn("bulletinRangeDays: BULLETIN_DEFAULT_RANGE_DAYS", js)
        self.assertIn("bulletinRangeSyncTimerId: null", js)
        self.assertIn("function getBulletinScheduleRange(", js)
        self.assertIn("function updateBulletinRangeSelection()", js)
        self.assertIn('getElementById("bulletinRangeSelect").addEventListener("change", updateBulletinRangeSelection)', js)
        self.assertIn("direction * days", js)
        self.assertIn("visibleEquipment = state.equipment.filter((equipment) => !isEquipmentDisabled(equipment));", js)
        self.assertIn("function renderReservationFloorplan(", js)
        self.assertIn('id="reservationFloorplanCanvas"', html)
        self.assertIn('id="reservationFloorplanOverlay"', html)
        self.assertIn("function openBulletinFullscreen()", js)
        self.assertIn("function openBulletinWindow()", js)
        self.assertIn("function scheduleBulletinAutoScroll(options = {})", js)
        self.assertIn("return scheduleBulletinAutoScrollWithOptions(options);", js)
        self.assertIn("function relayoutBulletinBoard(", js)
        self.assertIn("function syncBulletinRangeToToday()", js)
        self.assertIn("function scheduleBulletinRangeSync()", js)
        self.assertIn("function handleBulletinVisibilityChange()", js)
        self.assertIn('document.addEventListener("visibilitychange", handleBulletinVisibilityChange)', js)
        self.assertIn("const nextMidnight = startOfDay(addDays(now, 1));", js)
        self.assertIn("state.bulletinRangeSyncTimerId = window.setTimeout(", js)
        self.assertIn("function bindBulletinSettingsToggle()", js)
        self.assertIn('toggle.setAttribute("aria-expanded", settings.open ? "true" : "false");', js)
        self.assertIn('classList.toggle("bulletin-view-active"', js)
        self.assertIn("function stepBulletinAutoScroll()", js)
        self.assertIn("function updateBulletinScrollSettings()", js)
        self.assertIn("function getGanttBarStyle", js)
        self.assertIn("function getBulletinGanttMetrics(", js)
        self.assertIn("function getBulletinGanttBarMarkup(", js)
        self.assertNotIn("測試人：", js)
        self.assertNotIn("測試期間：", js)
        self.assertIn("project_name", js)
        self.assertIn(".gantt-chart", css)
        self.assertIn(".gantt-bar", css)
        self.assertIn(".bulletin-panel", css)
        self.assertIn(".bulletin-wrap", css)
        self.assertIn(".bulletin-settings", css)
        self.assertIn(".bulletin-settings-toggle", css)
        self.assertIn(".bulletin-controls", css)
        self.assertIn(".bulletin-bar", css)
        self.assertIn(".bulletin-scale .gantt-day > span", css)
        self.assertIn("text-overflow: ellipsis;", css)

    def test_reservation_form_has_project_name_and_no_week_schedule_panel(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('name="project_name"', html)
        self.assertIn('list="requesterNameOptions"', html)
        self.assertIn('list="requesterEmailOptions"', html)
        self.assertIn('value="PQE"', html)
        self.assertIn('id="requesterNameOptions"', html)
        self.assertIn('id="requesterEmailOptions"', html)
        self.assertIn('id="requesterNameMatches"', html)
        self.assertIn('id="requesterEmailMatches"', html)
        self.assertIn('name="test_condition"', html)
        self.assertNotIn('textarea name="notes" rows="3" placeholder=', html)
        self.assertIn("[hidden]", css)
        self.assertIn("project_name: payload.project_name.trim()", js)
        self.assertIn("function syncReservationEquipmentState()", js)
        self.assertIn("function isTruthyFlag(", js)
        self.assertIn("requires_test_condition", js)
        self.assertIn("test_condition", js)
        self.assertIn('.from("requester_directory")', js)
        self.assertIn("function loadRequesterDirectory()", js)
        self.assertIn("function renderRequesterOptions()", js)
        self.assertIn("function handleRequesterLookup", js)
        self.assertIn("function applyRequesterSuggestion", js)
        self.assertIn("function syncRequesterFields", js)
        self.assertIn(".typeahead-menu", css)
        self.assertNotIn('id="scheduleBoard"', html)
        self.assertNotIn("function renderWeek()", js)

    def test_legacy_excel_and_local_api_ui_is_removed(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertNotIn("/api/export.xlsx", html)
        self.assertNotIn("SharePoint Excel", html)
        self.assertNotIn('fetch("/api/', js)

    def test_dashboard_and_equipment_management_views_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="dashboardMetrics"', html)
        self.assertIn('data-view="reservation"', html)
        self.assertIn('data-view="equipment"', html)
        self.assertIn('data-view="requester"', html)
        self.assertIn('data-view="bulletin"', html)
        self.assertIn('id="equipmentFormTitle"', html)
        self.assertIn('id="equipmentCancelBtn"', html)
        self.assertIn('id="requesterForm"', html)
        self.assertIn('id="requesterSummary"', html)
        self.assertIn('id="requesterFormTitle"', html)
        self.assertIn('id="requesterCancelBtn"', html)
        self.assertIn('id="requesterResetBtn"', html)
        self.assertIn('name="requires_test_condition"', html)
        self.assertIn('name="equipment_spec"', html)
        self.assertIn('id="disabledEquipmentSection"', html)
        self.assertIn('id="disabledEquipmentList"', html)
        self.assertIn('id="disabledEquipmentCount"', html)
        self.assertIn('input name="capacity" type="text"', html)
        self.assertIn("可重疊預約量", js)
        self.assertNotIn('input name="capacity" type="number"', html)
        equipment_editor_html = html.split('id="equipmentEditorDialog"', 1)[1]
        self.assertNotIn('select name="is_active"', equipment_editor_html)
        self.assertIn('option value="validation"', html)
        self.assertIn("function renderDashboardMetrics()", js)
        self.assertIn("function startEditEquipment", js)
        self.assertIn("function syncEquipmentForm", js)
        self.assertIn("function cancelEquipmentEdit", js)
        self.assertIn("function submitRequester", js)
        self.assertIn("function renderRequesterSummary", js)
        self.assertIn("function startEditRequester", js)
        self.assertIn("function syncRequesterForm", js)
        self.assertIn("function cancelRequesterEdit", js)
        self.assertIn("function deleteRequester", js)
        self.assertIn('.order("is_active", { ascending: false })', js)
        self.assertIn(".filter((item) => item.is_active)", js)
        self.assertIn("function equipmentMatchesPayload", js)
        self.assertIn("function parseEquipmentCapacityLimit(", js)
        self.assertIn("equipment_spec", js)
        self.assertIn("equipmentSpecSupported", js)
        self.assertIn('isMissingColumnError(error, "equipment_spec")', js)
        self.assertIn("label_name", js)
        self.assertIn("equipmentLabelSupported", js)
        self.assertIn("function getFloorplanDisplayName", js)
        self.assertIn("function isEquipmentDisabled", js)
        self.assertIn("function renderDisabledEquipmentList", js)
        self.assertIn("getAllFloorplanPlacementsForRender", js)
        self.assertIn("function getFloorplanPlacementsForRender", js)
        self.assertIn(".filter((placement)", js)
        self.assertIn('form.elements.label_name.value = equipment.label_name || "";', js)
        self.assertNotIn("function normalizeTestCondition(", js)
        self.assertNotIn("function testConditionsMatch(", js)
        self.assertNotIn("assertCompatibleTestCondition", js)
        self.assertIn('statusText.validation = "驗證中"', js)
        self.assertIn(".metrics-grid", css)
        self.assertIn(".workspace-tab", css)
        self.assertIn(".equipment-card-actions", css)
        self.assertIn(".requester-card", css)
        self.assertIn(".badge.validation", css)
        self.assertIn(".floorplan-device.state-available", css)
        self.assertIn(".floorplan-device.state-validation", css)
        self.assertIn(".floorplan-device.state-maintenance", css)
        self.assertIn(".floorplan-device.is-disabled", css)
        self.assertIn(".disabled-equipment-section", css)
        self.assertIn(".disabled-equipment-row", css)
        self.assertIn('.workspace-view[data-view="equipment"] .equipment-layout', css)
        self.assertIn('.workspace-view[data-view="equipment"] .floorplan-grid', css)

    def test_gantt_reservation_detail_dialog_is_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="reservationDetailDialog"', html)
        self.assertIn('id="reservationDetailCopyBtn"', html)
        self.assertIn('id="reservationEditEmail"', html)
        self.assertIn('id="reservationEditUnlockBtn"', html)
        self.assertIn('id="reservationEditSaveBtn"', html)
        self.assertIn("function openReservationDetail(", js)
        self.assertIn("function getReservationViewModel(", js)
        self.assertIn("const view = getReservationViewModel(reservation);", js)
        self.assertIn("function getReservationDetailText(", js)
        self.assertIn("function configureReservationEdit(", js)
        self.assertIn("function unlockReservationEdit(", js)
        self.assertIn("function saveReservationEdit(", js)
        self.assertIn("function validateShortenedReservationWindow(", js)
        self.assertIn("function emailMatchesReservation(", js)
        self.assertIn('action: "updated"', js)
        self.assertIn("project_name", js)
        self.assertIn("start_time", js)
        self.assertIn("end_time", js)
        self.assertIn("navigator.clipboard.writeText", js)
        self.assertIn("reservation.project_name", js)
        self.assertIn(".reservation-detail-dialog", css)
        self.assertIn(".detail-grid", css)
        self.assertIn(".reservation-edit-panel", css)

    def test_gantt_overlap_stacking_and_equipment_zoom_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="equipmentScheduleDialog"', html)
        self.assertIn('id="equipmentScheduleChart"', html)
        self.assertIn("function layoutStackedReservations(", js)
        self.assertIn("function getEquipmentViewModel(", js)
        self.assertIn("const equipmentView = getEquipmentViewModel(equipment);", js)
        self.assertIn("function getDefaultGanttMetrics(", js)
        self.assertIn("function getMainGanttBarMarkup(", js)
        self.assertIn("function getStackedGanttBarStyle(", js)
        self.assertIn("function getVisibleStackedReservations(", js)
        self.assertIn("function getGanttLaneSummary(", js)
        self.assertIn("function applyRightEdgeFill(", js)
        self.assertIn("function isSingleDayReservation(", js)
        self.assertIn("if (!isSingleDayReservation(item.reservation))", js)
        self.assertIn("gantt-overflow-chip", js)
        self.assertIn("function openEquipmentSchedule(", js)
        self.assertIn("renderEquipmentScheduleDialog", js)
        self.assertIn("equipment-zoom-btn", js)
        self.assertIn(".gantt-bar.compact-bar", css)
        self.assertIn(".gantt-bar.project-requester", css)
        self.assertIn(".gantt-bar.project-only", css)
        self.assertIn("min-height: 0", css)
        self.assertIn(".gantt-overflow-chip", css)
        self.assertIn(".equipment-schedule-dialog", css)
        self.assertIn(".equipment-zoom-btn", css)

    def test_completed_reservations_release_time_and_render_soft_blue(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="reservationDetailCompleteBtn"', html)
        self.assertIn("function completeReservation(", js)
        self.assertIn("function getEffectiveReservationStatus(", js)
        self.assertIn("function canCompleteReservation(", js)
        self.assertIn('panel.hidden = isReadOnly', js)
        self.assertIn('getEffectiveReservationStatus(reservation) === "checked_out"', js)
        self.assertIn("statusLabel = statusText[effectiveStatus] || effectiveStatus", js)
        self.assertIn("return getReservationViewModel(reservation).detailRows", js)
        self.assertIn("checked_out:", js)
        self.assertIn('.neq("status", "checked_out")', js)
        self.assertIn("checked_out_at", js)
        self.assertIn('action: "completed"', js)
        self.assertIn(".gantt-bar.is-complete", css)
        self.assertIn(".badge.checked_out", css)

    def test_root_entry_is_the_real_frontend(self):
        root_html = (ROOT / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="reservationForm"', root_html)
        self.assertIn('./styles.css', root_html)
        self.assertIn('./app.js', root_html)
        self.assertNotIn("http-equiv=\"refresh\"", root_html)

    def test_floorplan_assets_and_fallback_hooks_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")
        seed = (STATIC / "assets" / "floorplan" / "equipment-floorplan-seed.json").read_text(encoding="utf-8")
        migration_sql = (STATIC / "supabase" / "migrations" / "20260814093000_equipment_floorplan_placements.sql").read_text(encoding="utf-8")
        manual_sql = (STATIC / "supabase" / "manual" / "20260814_equipment_floorplan_placements.sql").read_text(encoding="utf-8")

        self.assertIn('./assets/floorplan/equipment-floorplan-ui-transparent-clean.png', html)
        self.assertIn('id="floorplanOverlay"', html)
        self.assertIn('id="floorplanLayoutBtn"', html)
        self.assertIn('id="floorplanResetBtn"', html)
        self.assertIn('id="floorplanSaveBtn"', html)
        self.assertIn('id="floorplanSelectBtn"', html)
        self.assertIn('id="floorplanSelectionDetails"', html)
        self.assertIn('id="floorplanDeviceList"', html)
        self.assertIn("const FLOORPLAN_STORAGE_KEY =", js)
        self.assertIn("const FLOORPLAN_SEED_PLACEMENTS =", js)
        self.assertIn("function loadFloorplanPlacements()", js)
        self.assertIn("function hydrateFloorplanPlacementsFromFallback()", js)
        self.assertIn("function renderEquipmentFloorplan()", js)
        self.assertIn("function saveFloorplanLayout()", js)
        self.assertIn("function startEquipmentDraftPointer(", js)
        self.assertIn("function handleEquipmentDraftPointerMove(", js)
        self.assertIn("function saveEquipmentDraftPlacement(", js)
        self.assertIn('id="equipmentEditorDialog"', html)
        self.assertIn('id="equipmentDialogFloorplanOverlay"', html)
        self.assertIn('id="equipmentDialogPlacementMeta"', html)
        self.assertIn(".equipment-editor-dialog", css)
        self.assertIn(".equipment-editor-grid", css)
        self.assertIn(".floorplan-canvas", css)
        self.assertIn(".floorplan-device", css)
        self.assertIn(".floorplan-resize-handle", css)
        self.assertIn('"equipmentId": 17', seed)
        self.assertIn('"locationState": "unplaced"', seed)
        self.assertIn("create table if not exists public.equipment_floorplan_placements", migration_sql)
        self.assertIn('create policy "equipment_floorplan_public_write"', migration_sql)
        self.assertIn("grant select, insert, update on table public.equipment_floorplan_placements to anon, authenticated;", manual_sql)

    def test_equipment_label_name_sql_is_present(self):
        migration_sql = (STATIC / "supabase" / "migrations" / "20260817090000_equipment_label_name.sql").read_text(encoding="utf-8")
        manual_sql = (STATIC / "supabase" / "manual" / "20260817_equipment_label_name.sql").read_text(encoding="utf-8")

        self.assertIn("add column if not exists label_name text not null default ''", migration_sql)
        self.assertIn("comment on column public.equipment.label_name", migration_sql)
        self.assertIn("add column if not exists label_name text not null default ''", manual_sql)

    def test_capacity_text_manual_sql_is_present(self):
        sql = (STATIC / "supabase" / "manual" / "20260703_capacity_text.sql").read_text(encoding="utf-8")

        self.assertIn("alter table public.equipment", sql)
        self.assertIn("alter column capacity type text", sql)

    def test_equipment_utilization_analytics_assets_are_present(self):
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        js = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "styles.css").read_text(encoding="utf-8")

        self.assertIn('data-view-target="analytics"', html)
        self.assertIn('data-view="analytics"', html)
        self.assertIn('id="analyticsStartDate"', html)
        self.assertIn('id="analyticsEndDate"', html)
        self.assertIn('id="analyticsEquipmentSelect"', html)
        self.assertIn('id="analyticsCalculateBtn"', html)
        self.assertIn('id="analyticsExportBtn"', html)
        self.assertIn('id="analyticsPeriodDays"', html)
        self.assertIn('id="analyticsAvgBaseRate"', html)
        self.assertIn('id="analyticsAvgWeightedRate"', html)
        self.assertIn('id="analyticsTable"', html)
        self.assertIn('id="analyticsTableBody"', html)
        self.assertIn(".analytics-panel", css)
        self.assertIn(".analytics-kpi-grid", css)
        self.assertIn("function calculateEquipmentUtilization", js)
        self.assertIn("function renderUtilizationAnalytics", js)
        self.assertIn("function exportUtilizationToExcel", js)
        self.assertIn(".xlsx", js)
        self.assertIn("xlsx.full.min.js", html)

    def test_validation_equipment_is_bookable(self):
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertIn("function isEquipmentBookable(equipment)", js)
        self.assertIn('equipment.status === "available" || equipment.status === "validation"', js)
        self.assertIn('equipment.status === "maintenance"', js)
        self.assertIn("isEquipmentBookable(item)", js)
        self.assertIn("isEquipmentBookable(equipment)", js)

    def test_gantt_equipment_label_opens_readonly_equipment_dialog(self):
        js = (STATIC / "app.js").read_text(encoding="utf-8")

        self.assertIn('startEditEquipment(equipment.id, { readOnly: true })', js)
        self.assertIn("state.equipmentDialogReadOnly = isReadOnly", js)
        self.assertIn("openReservationFromGanttCell(equipment, date)", js)
        self.assertIn("if (!isEquipmentBookable(equipment))", js)


if __name__ == "__main__":
    unittest.main()

