create extension if not exists "pgcrypto";

create type public.equipment_status as enum (
  'available',
  'validation',
  'maintenance',
  'offline'
);

create type public.reservation_status as enum (
  'reserved',
  'cancelled',
  'checked_in',
  'checked_out'
);

create type public.approval_status as enum (
  'not_required',
  'pending',
  'approved',
  'rejected'
);

create type public.user_role as enum (
  'user',
  'lab_admin',
  'manager'
);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null unique,
  department text not null default '',
  role public.user_role not null default 'user',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  location text not null default '',
  status public.equipment_status not null default 'available',
  capacity integer not null default 1 check (capacity >= 1),
  equipment_spec text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references public.equipment (id) on delete restrict,
  requester_id uuid references public.profiles (id) on delete set null,
  requester_name text not null,
  requester_email text not null,
  department text not null,
  project_name text not null default '',
  purpose text not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status public.reservation_status not null default 'reserved',
  approval_status public.approval_status not null default 'not_required',
  checked_in_at timestamptz,
  checked_out_at timestamptz,
  notes text not null default '',
  cancel_reason text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint reservations_time_check check (end_time > start_time)
);

create table if not exists public.reservation_history (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations (id) on delete cascade,
  action text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references public.profiles (id) on delete set null,
  changed_by_name text not null default 'system',
  changed_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_equipment_status on public.equipment (status, is_active);
create index if not exists idx_reservations_equipment_time on public.reservations (equipment_id, start_time, end_time);
create index if not exists idx_reservations_requester on public.reservations (requester_id);
create index if not exists idx_reservation_history_reservation on public.reservation_history (reservation_id, changed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_equipment_updated_at on public.equipment;
create trigger trg_equipment_updated_at
before update on public.equipment
for each row
execute function public.set_updated_at();

drop trigger if exists trg_reservations_updated_at on public.reservations;
create trigger trg_reservations_updated_at
before update on public.reservations
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.equipment enable row level security;
alter table public.reservations enable row level security;
alter table public.reservation_history enable row level security;
