create table if not exists public.requester_directory (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  department text not null default 'PQE',
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.requester_directory enable row level security;

grant select, insert, update on table public.requester_directory to anon, authenticated;
grant usage, select on sequence public.requester_directory_id_seq to anon, authenticated;

drop policy if exists "requester_directory_public_read" on public.requester_directory;
create policy "requester_directory_public_read"
on public.requester_directory
for select
to anon, authenticated
using (true);

drop policy if exists "requester_directory_public_insert" on public.requester_directory;
create policy "requester_directory_public_insert"
on public.requester_directory
for insert
to anon, authenticated
with check (true);

drop policy if exists "requester_directory_public_update" on public.requester_directory;
create policy "requester_directory_public_update"
on public.requester_directory
for update
to anon, authenticated
using (true)
with check (true);

insert into public.requester_directory (name, email, department, sort_order)
values
  ('Hank.Wu(吳金龍)', 'Hank.Wu@senao.com', 'PQE', 10),
  ('Kamber.Yeh(葉志健)', 'Kamber.Yeh@senao.com', 'PQE', 20),
  ('Andys.Huang(黃健勝)', 'Andys.Huang@senao.com', 'PQE', 30),
  ('Norman.Chien(簡佑丞)', 'Norman.Chien@senao.com', 'PQE', 40),
  ('Rita.Lin(林庭如)', 'Rita.Lin@senao.com', 'PQE', 50)
on conflict (email) do update
set
  name = excluded.name,
  department = excluded.department,
  sort_order = excluded.sort_order,
  is_active = true;
